#!/bin/bash -e

if ! mas account >&-; then
  if [ -z "$APPLE_ID" ]; then
      read -r -p "Apple ID: " APPLE_ID
  fi
  mas signin "${APPLE_ID}"
fi

pushd "${BASE_PATH}/mas" >&-
  for pkg in *
  do
    echo "Installing ${pkg}"
    mas install "$(cat "${pkg}")"
  done
popd >&-
