#!/bin/bash -e

installed_formulae="$(brew list)"

pushd "${BASE_PATH}/homebrew/formulae" >&-
  for formula in *
  do
    if ! grep -qe "^$formula" < <(echo "$installed_formulae")
    then
      if [ -z "$formula_options" ]
      then
        brew install "$formula"
      else
        brew install "$formula" "$formula_options"
      fi
    fi
  done
popd >&-
